-- MySQL Script generated by MySQL Workbench
-- 10/24/14 08:19:50
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema reportame
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `reportame` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `reportame` ;

-- -----------------------------------------------------
-- Table `reportame`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `alias` VARCHAR(75) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `tipoUsuario` INT NOT NULL DEFAULT 2 COMMENT 'Tipo de usuario sera:' /* comment truncated */ /*1 Administrador
2 Ciudadano
3 Gobierno
4 Empresa */,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idUsuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Tabla que almacenara los datos basicos de los usuarios';


-- -----------------------------------------------------
-- Table `reportame`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Tabla de categorias para eventos, enfermedad, operativo, etc' /* comment truncated */ /*.*/;


-- -----------------------------------------------------
-- Table `reportame`.`Enfermedad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Enfermedad` (
  `idEnfermedad` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `imagePing` VARCHAR(120) NULL,
  `imagePingShadow` VARCHAR(120) NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idEnfermedad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reportame`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Perfil` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `firtsName` VARCHAR(75) NULL,
  `lastName` VARCHAR(75) NULL,
  `phone` VARCHAR(15) NULL,
  `cellphone` VARCHAR(15) NULL,
  `birthday` DATE NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `municipio` VARCHAR(75) NULL,
  `sex` TINYINT(1) NULL,
  `profesion` VARCHAR(75) NULL,
  `usuario_id` INT NOT NULL,
  `documentType` VARCHAR(45) NULL,
  `estadoCivil` VARCHAR(45) NULL,
  `numeroHijos` INT NULL,
  `peso` INT NULL,
  `tipoSangre` VARCHAR(45) NULL,
  `owner` TINYINT(1) NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` TINYINT(1) NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  PRIMARY KEY (`idPerfil`),
  UNIQUE INDEX `idPerfil_UNIQUE` (`idPerfil` ASC),
  INDEX `fk_Perfil_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Perfil_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `reportame`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reportame`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Evento` (
  `idEvento` INT NOT NULL AUTO_INCREMENT,
  `lat` FLOAT NOT NULL,
  `lon` FLOAT NOT NULL,
  `usuario_id` INT NOT NULL,
  `categoria_id` INT NOT NULL,
  `enfermedad_id` INT NULL,
  `descripcion` VARCHAR(250) NULL,
  `perfil_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Usuario_idx` (`usuario_id` ASC),
  INDEX `fk_Evento_Categoria1_idx` (`categoria_id` ASC),
  INDEX `fk_Evento_Enfermedad1_idx` (`enfermedad_id` ASC),
  INDEX `fk_Evento_Perfil_idx` (`perfil_id` ASC),
  CONSTRAINT `fk_Evento_Usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `reportame`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `reportame`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Enfermedad1`
    FOREIGN KEY (`enfermedad_id`)
    REFERENCES `reportame`.`Enfermedad` (`idEnfermedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Perfil`
    FOREIGN KEY (`perfil_id`)
    REFERENCES `reportame`.`Perfil` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Tabla que almacenara los eventos';


-- -----------------------------------------------------
-- Table `reportame`.`Consejo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Consejo` (
  `idConsejo` INT NOT NULL AUTO_INCREMENT,
  `consejo` VARCHAR(250) NOT NULL,
  `usuario_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL COMMENT '	',
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idConsejo`),
  UNIQUE INDEX `idComentario_UNIQUE` (`idConsejo` ASC),
  INDEX `fk_Consejo_Usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Consejo_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `reportame`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = 'Un evento puede tener N comentarios';


-- -----------------------------------------------------
-- Table `reportame`.`ConsejoAds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`ConsejoAds` (
  `idConsejoAds` INT NOT NULL AUTO_INCREMENT,
  `consejo` VARCHAR(250) NOT NULL,
  `usuario_id` INT NOT NULL,
  `caducidad` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idConsejoAds`),
  INDEX `fk_ConsejoAds_Usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_ConsejoAds_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `reportame`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reportame`.`Likeflag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Likeflag` (
  `idLikeflag` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `consejo_id` INT NULL,
  `consejoAds_id` INT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idLikeflag`),
  INDEX `fk_Likeflag_Usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_Likeflag_Consejo1_idx` (`consejo_id` ASC),
  INDEX `fk_Likeflag_ConsejoAds1_idx` (`consejoAds_id` ASC),
  CONSTRAINT `fk_Likeflag_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `reportame`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likeflag_Consejo1`
    FOREIGN KEY (`consejo_id`)
    REFERENCES `reportame`.`Consejo` (`idConsejo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Likeflag_ConsejoAds1`
    FOREIGN KEY (`consejoAds_id`)
    REFERENCES `reportame`.`ConsejoAds` (`idConsejoAds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reportame`.`Reportflag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Reportflag` (
  `Reportflag` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `consejo_id` INT NULL,
  `consejoAds_id` INT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`Reportflag`),
  INDEX `fk_Reportflag_Usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_Reportflag_Consejo1_idx` (`consejo_id` ASC),
  INDEX `fk_Reportflag_ConsejoAds1_idx` (`consejoAds_id` ASC),
  CONSTRAINT `fk_Reportflag_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `reportame`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportflag_Consejo1`
    FOREIGN KEY (`consejo_id`)
    REFERENCES `reportame`.`Consejo` (`idConsejo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportflag_ConsejoAds1`
    FOREIGN KEY (`consejoAds_id`)
    REFERENCES `reportame`.`ConsejoAds` (`idConsejoAds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reportame`.`Label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`Label` (
  `idLabel` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(75) NOT NULL,
  `usuario_id` INT NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`idLabel`),
  INDEX `fk_Label_Usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_Label_Usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `reportame`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reportame`.`EventoLabel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`EventoLabel` (
  `idEventoLabel` INT NOT NULL AUTO_INCREMENT,
  `evento_id` INT NOT NULL,
  `label_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idEventoLabel`),
  UNIQUE INDEX `idEventoLabel_UNIQUE` (`idEventoLabel` ASC),
  INDEX `fk_EventoLabel_Label1_idx` (`label_id` ASC),
  INDEX `fk_EventoLabel_Evento1_idx` (`evento_id` ASC),
  CONSTRAINT `fk_EventoLabel_Label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `reportame`.`Label` (`idLabel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EventoLabel_Evento1`
    FOREIGN KEY (`evento_id`)
    REFERENCES `reportame`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `reportame`.`ConsejoAdsLabel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`ConsejoAdsLabel` (
  `idConsejoAdsLabel` INT NOT NULL AUTO_INCREMENT,
  `consejoAds_id` INT NOT NULL,
  `label_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idConsejoAdsLabel`),
  INDEX `fk_ConsejoAdsLabel_Label1_idx` (`label_id` ASC),
  INDEX `fk_ConsejoAdsLabel_ConsejoAds1_idx` (`consejoAds_id` ASC),
  CONSTRAINT `fk_ConsejoAdsLabel_Label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `reportame`.`Label` (`idLabel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConsejoAdsLabel_ConsejoAds1`
    FOREIGN KEY (`consejoAds_id`)
    REFERENCES `reportame`.`ConsejoAds` (`idConsejoAds`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reportame`.`ConsejoLabel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reportame`.`ConsejoLabel` (
  `idConsejoLabel` INT NOT NULL AUTO_INCREMENT,
  `label_id` INT NOT NULL,
  `consejo_id` INT NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`idConsejoLabel`),
  INDEX `fk_ConsejoLabel_Consejo1_idx` (`consejo_id` ASC),
  INDEX `fk_ConsejoLabel_Label1_idx` (`label_id` ASC),
  CONSTRAINT `fk_ConsejoLabel_Consejo1`
    FOREIGN KEY (`consejo_id`)
    REFERENCES `reportame`.`Consejo` (`idConsejo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConsejoLabel_Label1`
    FOREIGN KEY (`label_id`)
    REFERENCES `reportame`.`Label` (`idLabel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
